### ISSUE TITLE
The script is getting the wrong time on this exit

### ISSUE THREAD

**Issue by kalimalrazif** [glensc/monitoring-plugin-check_domain#61] opened 2016-06-28 18:27 UTC
Hello:
I'm getting this exit 
```
CRITICAL - Domain domain expired 662751 days ago (0201-12-10). | domain_days_until_expiry=-662751;30;7
```
with this whois exit:

```
created:     20141210 #13644956
expires:     20161210
changed:     20141210
```

thanks in advance
Nomar

**Comment by kalimalrazif** [comment] 2016-06-28 18:38
Sorry I forgot to comment the domain is a .com.br domain

**Comment by glensc** [comment] 2016-07-04 10:44
need exact domain name to test with

**Comment by kalimalrazif** [comment] 2016-07-04 14:56
ok :-)

recarga-celular-tim-sa.com.br

recarga-brasil-telecom.com.br



[image: --]

Nomar Mora
[image: http://]about.me/nomar.mora
<http://about.me/nomar.mora?promo=email_sig>

**Comment by glensc** [comment] 2016-07-04 17:54
seems i'm banned to use whois of those domains (likely restricted to networks in BR only). could you attach output somewhere?

```
[~/scm/nagios/check_domain (master)⚡] ➔ ./test.sh recarga-celular-tim-sa.com.br
-> recarga-celular-tim-sa.com.br
UNKNOWN - Rate limited WHOIS response
<- recarga-celular-tim-sa.com.br
[~/scm/nagios/check_domain (master)⚡] ➔ ./test.sh recarga-brasil-telecom.com.br
-> recarga-brasil-telecom.com.br
UNKNOWN - Rate limited WHOIS response
<- recarga-brasil-telecom.com.br
[~/scm/nagios/check_domain (master)⚡] ➔ 
```

**Comment by kalimalrazif** [comment] 2016-07-04 18:08
./check_domain -d recarga-celular-tim-sa.com.br
CRITICAL - Domain recarga-celular-tim-sa.com.br expired 662753 days ago
(0201-12-14). | domain_days_until_expiry=-662753;30;7

./check_domain -d recarga-brasil-telecom.com.br
CRITICAL - Domain recarga-brasil-telecom.com.br expired 662757 days ago
(0201-12-10). | domain_days_until_expiry=-662757;30;7



[image: --]

Nomar Mora
[image: http://]about.me/nomar.mora
<http://about.me/nomar.mora?promo=email_sig>

**Comment by glensc** [comment] 2016-07-04 18:49
come on dude, i need output of the whois command!

**Comment by kalimalrazif** [comment] 2016-07-05 01:45
Omg sorry man! I got it wrong :-( got confused by your output

whois recarga-celular-tim-sa.com.br

% Copyright (c) Nic.br
%  The use of the data below is only permitted as described in
%  full by the terms of use at http://registro.br/termo/en.html ,
%  being prohibited its distribution, commercialization or
%  reproduction, in particular, to use it for advertising or
%  any similar purpose.
%  2016-07-04 22:43:18 (BRT -03:00)

% Query rate limit exceeded. Reduced information.
% Use https://registro.br/cgi-bin/nicbr/busca_dominio for domain
availability.

domain:      recarga-celular-tim-sa.com.br
owner:       Josefina Aguilar
country:     BR
owner-c:     JOAGU105
admin-c:     JOAGU105
tech-c:      JOAGU105
billing-c:   JOAGU105
nserver:     ns-1283.awsdns-32.org
nsstat:      20160704 AA
nslastaa:    20160704
nserver:     ns-1626.awsdns-11.co.uk
nsstat:      20160704 AA
nslastaa:    20160704
nserver:     ns-224.awsdns-28.com
nsstat:      20160704 AA
nslastaa:    20160704
nserver:     ns-957.awsdns-55.net
nsstat:      20160704 AA
nslastaa:    20160704
saci:        yes
created:     20151214 #15024780
expires:     20161214
changed:     20151218
status:      published

nic-hdl-br:  JOAGU105
person:      Josefina Aguilar
created:     20141210
changed:     20151204

% Security and mail abuse issues should also be addressed to
% cert.br, http://www.cert.br/ , respectivelly to cert@cert.br
% and mail-abuse@cert.br
%
% whois.registro.br accepts only direct match queries. Types
% of queries are: domain (.br), registrant (tax ID), ticket,
% provider, contact handle (ID), CIDR block, IP and ASN.

whois recarga-brasil-telecom.com.br

% Copyright (c) Nic.br
%  The use of the data below is only permitted as described in
%  full by the terms of use at http://registro.br/termo/en.html ,
%  being prohibited its distribution, commercialization or
%  reproduction, in particular, to use it for advertising or
%  any similar purpose.
%  2016-07-04 22:44:28 (BRT -03:00)

% Query rate limit exceeded. Reduced information.
% Use https://registro.br/cgi-bin/nicbr/busca_dominio for domain
availability.

domain:      recarga-brasil-telecom.com.br
owner:       Josefina Aguilar
country:     BR
owner-c:     JOAGU105
admin-c:     JOAGU105
tech-c:      JOAGU105
billing-c:   JOAGU105
nserver:     ns-1184.awsdns-20.org
nsstat:      20160701 AA
nslastaa:    20160701
nserver:     ns-1557.awsdns-02.co.uk
nsstat:      20160701 AA
nslastaa:    20160701
nserver:     ns-371.awsdns-46.com
nsstat:      20160701 AA
nslastaa:    20160701
nserver:     ns-982.awsdns-58.net
nsstat:      20160701 AA
nslastaa:    20160701
saci:        yes
created:     20141210 #13644871
expires:     20161210
changed:     20141210
status:      published

nic-hdl-br:  JOAGU105
person:      Josefina Aguilar
created:     20141210
changed:     20151204

% Security and mail abuse issues should also be addressed to
% cert.br, http://www.cert.br/ , respectivelly to cert@cert.br
% and mail-abuse@cert.br
%
% whois.registro.br accepts only direct match queries. Types
% of queries are: domain (.br), registrant (tax ID), ticket,
% provider, contact handle (ID), CIDR block, IP and ASN.

**Comment by glensc** [comment] 2016-07-05 13:37
Your output is also rate limited, matches `Query rate limit exceeded. Reduced information.` so it's no use.

and next time please ATTACH the output, not post in comment body. in such programs it is very important to retain the exact formatting of newlines, spaces wrapping in case i do not have access to real data.

**Comment by glensc** [comment] 2016-07-05 14:49
come on, which part of you do not understand you need to attach the file, not post it!?!

**Comment by kalimalrazif** [comment] 2016-07-06 11:12
Yes I attach files, but you know? Let's leave this up here, each and every one
of the developers on github I've contacted has been polite and friendly, until
I contact you.

I will not longer use the plugin .. thanks I apologize for wasting your
time.

Bye.



[image: --]

Nomar Mora
[image: http://]about.me/nomar.mora
<http://about.me/nomar.mora?promo=email_sig>

**Comment by glensc** [comment] 2016-07-07 10:32
i explained you several times why the output needs to be unmodified, but you still did not provide such and even skipped the other important questions.

i told you first time i am not able to reproduce this because you do not provide exact environment details you run it.

please read again my posts, and see:
- explained why need unmodified output (not mangled newlines, or spacing)
- what version you run

you never responded accordingly and i still can not resolve your issue because i am not able to reproduce it

**Comment by kalimalrazif** [comment] 2016-07-07 13:12
There are the files, I have absolute no idea that the email posts were put here, I attach the files from gmail
[002.txt](https://github.com/glensc/monitoring-plugin-check_domain/files/352178/002.txt)
[001.txt](https://github.com/glensc/monitoring-plugin-check_domain/files/352179/001.txt)
Have a good day sir.

Once again I apologize for wasting your time. Please do not further contact me

**Comment by glensc** [comment] 2016-07-07 18:25
saved:
- 001.txt as data/whois_recarga-celular-tim-sa.com.br.txt
- 002.txt as data/whois_recarga-brasil-telecom.com.br.txt

and tested with:

```
$ ./test.sh recarga-celular-tim-sa.com.br
-> recarga-celular-tim-sa.com.br
OK - Domain recarga-celular-tim-sa.com.br will expire in 159 days (2016-12-14). | domain_days_until_expiry=159;30;7
<- recarga-celular-tim-sa.com.br

$ ./test.sh recarga-brasil-telecom.com.br
-> recarga-brasil-telecom.com.br
OK - Domain recarga-brasil-telecom.com.br will expire in 155 days (2016-12-10). | domain_days_until_expiry=155;30;7
<- recarga-brasil-telecom.com.br
```

works for me. and you still haven't responded do you even use right version.

**Comment by glensc** [comment] 2016-08-25 19:58
unable to reproduce, closing

**Closed by glensc** 2016-08-25 19:58 UTC
