### ISSUE TITLE
No Response return in LibreNMS

### ISSUE THREAD

**Issue by Cool76** [glensc/monitoring-plugin-check_domain#94] opened 2019-07-15 10:00 UTC
no problem when run on check_domain.sh 
[librenms@localhost plugins]$ ./check_domain.sh -d google.com
OK - Domain google.com will expire in 425 days (2020-09-13). | domain_days_until_expiry=425;30;7

however  ./check-services.php not work
Nagios Service - 4  
Request:  '/usr/lib64/nagios/plugins/check_domain.sh' '-H' 'GOOGLE.COM' '-d'  
check_domain.sh: invalid option -- 'H'
check_domain.sh: option requires an argument -- 'd'
Perf Data - None.  
Response:  
./check-services.php 2019-07-15 17:45:32 - 2 services polled in 0.385 secs  

thanks for help

**Comment by glensc** [comment] 2019-07-16 16:06
duplicate of #89

**Closed by glensc** 2019-07-16 16:06 UTC
