### ISSUE TITLE
The Script does not work properly with .com Domains

### ISSUE THREAD

**Issue by Busindre** [glensc/monitoring-plugin-check_domain#76] opened 2017-08-20 15:17 UTC
Hi!.

The Script does not work properly with .com Domains
```
bash /usr/local/nagios/libexec/check_domain.sh -d  githubusercontent.com
UNKNOWN - WHOIS exited with error 1.

bash /usr/local/nagios/libexec/check_domain.sh -d  freetsa.org          
OK - Domain freetsa.org will expire in 119 days (2017-12-18). | domain_days_until_expiry=119;30;7
```
whois Version: RIPE Database Query Service version 1.89.2 

Regards

**Comment by glensc** [comment] 2017-08-22 14:50
duplicate of #75

**Closed by glensc** 2017-08-22 14:50 UTC
